{% set name = "stereo-pipeline" %}

{% set version = "3.5.0_minimal" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/visionworkbench/visionworkbench/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2d74995416f989fd23dd38f4035e0328259286222cb3dd28cc86eb7ff00ae263

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake >=3.15
    - make
    - c-compiler 1.8.0
    - cxx-compiler 1.8.0
    - {{ stdlib('c') }}
    - wget

  host:
    - libgdal-core
    - llvm-openmp
    - flann
    - openssl
    - libssh2
    - blas
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libopenblas
    - openblas
    - libopencv
    - opencv
    - proj
    - hdf5
    - libzlib
    - zlib
    - libboost-devel
    - libjpeg-turbo
    - libtiff
    - libpng
    - lz4-c
    - libstdcxx  # [linux]
    - libgcc  # [linux]
    - libcxx  # [osx]
    # The packages below will go to the stereo-pipeline feedstock
    - chrpath  # [linux]
    - libglvnd  # [linux]
    - parallel
    - pbzip2
    - krb5
    - libpdal-core
    - ale
    - usgscsm
    - eigen
    - ceres-solver
    #- cspice =67
    #- csm >=3.0.3,<3.0.4
    - libcurl
    - curl
    - gflags
    - glog
    - geotiff
    # - libprotobuf >=4,<5
    # - protobuf >=4,<5
    - libxml2
    - mesalib
    - mysql
    - nlohmann_json
    # The pcl package fails no matter what
    # - pcl
    # - python
    # - python_abi
    - qt-main
    - qwt
    - tbb
    - tbb-devel
    - xerces-c
    - xorg-kbproto
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxi

  run:
    - libgdal-core
    - llvm-openmp
    - flann
    - openssl
    - libssh2
    - blas
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libopenblas
    - openblas
    - libopencv
    - opencv
    - proj
    - hdf5
    - libzlib
    - zlib
    - libboost-devel
    - libjpeg-turbo
    - libtiff
    - libpng
    - lz4-c
    - libstdcxx  # [linux]
    - libgcc  # [linux]
    - libcxx  # [osx]
    # The packages below will go to the stereo-pipeline feedstock
    - chrpath  # [linux]
    - libglvnd  # [linux]
    - parallel
    - pbzip2
    - krb5
    - libpdal-core
    - ale
    - usgscsm
    - eigen
    - ceres-solver
    - cspice =67
    #- csm >=3.0.3,<3.0.4
    - libcurl
    - curl
    - gflags
    - glog
    - geotiff
    # - libprotobuf >=4,<5
    # - protobuf >=4,<5
    - libxml2
    - mesalib
    - mysql
    - nlohmann_json
    # The pcl package fails no matter what
    # - pcl
    # - python
    # - python_abi
    - qt-main
    - qwt
    - tbb
    - tbb-devel
    - xerces-c
    - xorg-kbproto
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxi

test:
  commands:
    - echo success
    - test -f $PREFIX/bin/hillshade  # [unix]

about:
  home: https://github.com/NeoGeographyToolkit/StereoPipeline
  summary: 'A suite of tools for producing terrain models published by NASA'
  description: |
    The NASA Ames Stereo Pipeline is a collection of tools for producing 3D terrain models from images acquired by satellites of planets and of Earth. It also supports alignment of terrains, correction of errors in camera positions and orientations, and structure from motion.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://stereopipeline.readthedocs.io/en/latest/index.html
  dev_url: https://stereopipeline.readthedocs.io/en/latest/building_asp.html

extra:
  recipe-maintainers:
    - oleg-alexandrov
