{% set name = "visionworkbench" %}

{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/visionworkbench/visionworkbench/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2d74995416f989fd23dd38f4035e0328259286222cb3dd28cc86eb7ff00ae263

build:
  number: 0

requirements:
  build:
    - cmake >=3.15
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

  host:
    - libgdal                   3.7.1
    - llvm-openmp               16.0.6
    - flann                     1.9.1
    - openssl                   3.1.8
    - libssh2                   1.11.0
    - blas                      2.131
    - blas-devel                3.9.0
    - libblas                   3.9.0
    - libcblas                  3.9.0
    - liblapack                 3.9.0
    - liblapacke                3.9.0
    - libopenblas               0.3.29
    - openblas                  0.3.29
    - libopencv                 4.7.0
    - opencv                    4.7.0
    - proj                      9.2.1
    - hdf5                      1.14.1
    - libzlib                   1.3.1
    - zlib                      1.3.1
    - boost                     1.78.0
    - boost-cpp                 1.78.0

  run:
    - libgdal                   3.7.1
    - llvm-openmp               16.0.6
    - flann                     1.9.1
    - openssl                   3.1.8
    - libssh2                   1.11.0
    - blas                      2.131
    - blas-devel                3.9.0
    - libblas                   3.9.0
    - libcblas                  3.9.0
    - liblapack                 3.9.0
    - liblapacke                3.9.0
    - libopenblas               0.3.29
    - openblas                  0.3.29
    - libopencv                 4.7.0
    - opencv                    4.7.0
    - proj                      9.2.1
    - hdf5                      1.14.1
    - libzlib                   1.3.1
    - zlib                      1.3.1
    - boost                     1.78.0
    - boost-cpp                 1.78.0

test:
  commands:
    - hillshade --version

about:
  home: https://github.com/visionworkbench/visionworkbench
  summary: 'A general purpose image processing and computer vision library'
  description: |
    The NASA Vision Workbench is a general purpose image processing and computer vision library.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/visionworkbench/visionworkbench
  dev_url: https://github.com/visionworkbench/visionworkbench

extra:
  recipe-maintainers:
    - oleg-alexandrov
