context:
  name: visionworkbench
  version: "3.5.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/visionworkbench/visionworkbench/archive/refs/tags/${{ version }}.tar.gz
  sha256: 4f1fcfff3a2ae058496b2b78437195dc073423a57d1a9db05a24782961278a2f

build:
  number: 0
  skip: win
  script: build.sh

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake >=3.15
    - make
  host:
    - blas-devel
    - blis
    - flann
    - libboost-devel
    - libgdal
    - liblapack
    - libopenblas
    - libopencv
    - openexr
    # gdal will bring all these, but they are also direct as specified in the README.
    - libjpeg-turbo
    - libpng
    - libtiff
  run:
    - blis  # I believe run_exports
    - openexr

tests:
  - script:
    - hillshade $PREFIX/share/vw/tests/tinyDemAN.tif

about:
  homepage: https://github.com/visionworkbench/visionworkbench
  summary: 'An image processing and computer vision library published by NASA'
  description: |
    The NASA Vision Workbench is a general purpose image processing and computer vision library. It is used by NASA for processing images of planetary bodies.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  documentation: https://github.com/visionworkbench/visionworkbench
  repository: https://github.com/visionworkbench/visionworkbench

extra:
  recipe-maintainers:
    - oleg-alexandrov