{% set name = "flyr" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flyr-{{ version }}.tar.gz
  sha256: 01dbae05fe1e16dadb13480181520809124aa0424281492f836fd607311544c6

build:
  entry_points:
    - flyr=flyr.flyr:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - setuptools
    - python
    - pip
  run:
    - python
    - numpy
    - pillow

test:
  imports:
    - flyr
  commands:
    - pip check
    - flyr --help
  requires:
    - python
    - pip

about:
  home: https://bitbucket.org/nimmerwoner/flyr/
  summary: Flyr is a library for extracting thermal data from FLIR images written fully in Python, without depending on ExifTool.
  license: EUPL-1.2
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AFis-245
    - nfahlgren
