{% set name = "flyr" %}
{% set version = "3.4.1" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flyr-{{ version }}.tar.gz
  sha256: c518498105b4795a3f2e0003b5896df5c54a45334335294e688b1fcc5af930b8

build:
  entry_points:
    - flyr=flyr.flyr:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - setuptools
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - nptyping ==0.3.1
    - pillow

test:
  imports:
    - flyr
  commands:
    - pip check
    - flyr --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://bitbucket.org/nimmerwoner/flyr/
  summary: Flyr is a library for extracting thermal data from FLIR images written fully in Python, without depending on ExifTool.
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AFis-245
    - nfahlgren
